### ISSUE TITLE
安装easyquant时报错

### ISSUE THREAD

**Issue by yoyobbs** [shidenggui/easyquant#44]
作者您好，我在ubuntu上安装了easyquant,库都已经安装好了，我是使用雪球登录的，但是在运行test.py的时候，报错了markup未定义，不知道您在调试的时候是否也有这个问题？或者您可以指点一下方向？感谢您。
————————————————————————————————————————————
brian@ubuntu:~/py/easyquant$ python3 test.py
easyquant 测试 DEMO
请输入你使用的券商:
1: 华泰 2: 佣金宝 3: 银河 4: 雪球模拟组合 5: 广发
:4
请输入你的帐号配置文件路径(直接回车使用 xq.json)
:
请输入使用行情引擎 1: sina 2: leverfun 十档 行情(目前只选择了 162411, 000002)
:1
请输入行情推送间隔(s)
:10
请输入 log 记录方式: 1: 显示在屏幕 2: 记录到指定文件
: 1
[2016-06-27 21:32:21.421482] DEBUG: xqtrader.py: login status: SUCCESS
[2016-06-27 21:32:21.467099] INFO: 测试: 启动主引擎
[2016-06-27 21:32:21.474106] INFO: 测试: 加载策略: 策略2_Demo
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    m.load_strategy()
  File "/home/brian/py/easyquant/easyquant/main_engine.py", line 86, in load_strategy
    self.strategy_list.append(strategy_class(log_handler=self.log, main_engine=self))
  File "/home/brian/py/easyquant/easyquant/strategy/strategyTemplate.py", line 19, in **init**
    self.init()
  File "/home/brian/py/easyquant/strategies/策略1_Demo.py", line 16, in init
    self.clock_engine.register_moment(clock_type, moment)
  File "/home/brian/py/easyquant/easyquant/push_engine/clock_engine.py", line 233, in register_moment
    return self._register_moment(clock_type, moment, makeup=markup)
NameError: name 'markup' is not defined

brian@ubuntu:~/py/easyquant$ python3 -m pip install markup
Requirement already satisfied (use --upgrade to upgrade): markup in /usr/local/lib/python3.5/dist-packages

**Comment by yoyobbs** [comment]
作者您好，把File "/home/brian/py/easyquant/easyquant/push_engine/clock_engine.py", line 233, in register_moment
return self._register_moment(clock_type, moment, makeup=markup)
中的markup修改成makeup即可了。

**Comment by shidenggui** [comment]
这个最新版本已经修改过了，你下的应该是旧版本。
