### ISSUE TITLE
2017/9/7日，广发登录后报错

### ISSUE THREAD

**Issue by matrixleon18** [shidenggui/easyquant#58]
Traceback (most recent call last):
  File "test.py", line 100, in <module>
    m = easyquant.MainEngine(broker_data, account_data, quotation_engines=[quotation_engine], log_handler=log_data)
  File "D:\easyquant\easyquant\main_engine.py", line 44, in __init__
    self.user.prepare(need_data)
  File "C:\Python36\lib\site-packages\easytrader\webtrader.py", line 73, in prepare
    self.autologin()
  File "C:\Python36\lib\site-packages\easytrader\webtrader.py", line 84, in autologin
    if self.login():
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 78, in login
    login_status, result = self.post_login_data(verify_code)
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 96, in post_login_data
    self.__set_trade_need_info()
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 155, in __set_trade_need_info
    jsholder = eval(jsholder[0])
IndexError: list index out of range

**Comment by matrixleon18** [comment]
Useless
